version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk-network

  kibana:
    image: kibana:${ELASTIC_VERSION}
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=${KIBANA_HOST}
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - elk-network

  logstash:
    image: logstash:${ELASTIC_VERSION}
    container_name: logstash
    environment:
      - LOGSTASH_USER=${LOGSTASH_USER}
      - LOGSTASH_PASSWORD=${LOGSTASH_PASSWORD}
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - ${LOGSTASH_BEATS_PORT}:${LOGSTASH_BEATS_PORT}
      - ${LOGSTASH_TCP_PORT}:${LOGSTASH_TCP_PORT}/tcp
      - ${LOGSTASH_TCP_PORT}:${LOGSTASH_TCP_PORT}/udp
      - "9600:9600"
    networks:
      - elk-network

  filebeat:
    image: docker.elastic.co/beats/filebeat:${ELASTIC_VERSION}
#    build:
#      context: ./filebeat
#      dockerfile: Dockerfile
    container_name: filebeat
    user: root
    depends_on:
      - logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/log:/var/log:ro
    networks:
      - elk-network


  accounting-api:
    build:
      context: ./accounting-service
      dockerfile: Dockerfile
    container_name: accounting-api
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "7070:7070"
    networks:
      - elk-network

  income-api:
    build:
      context: ./income-service
      dockerfile: Dockerfile
    container_name: income-api
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=default
    ports:
      - "7071:7071"
    networks:
      - elk-network

volumes:
  elasticsearch_data:

networks:
  elk-network:
    driver: bridge